config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :services

  namespace :admin do
    root to: 'pages#home'
    resources :users
    resources :services
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :description, presence: true
  validates :image, presence: true
  validates :category_id, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < AdminController
    def home; end


  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < AdminController
    before_action :set_service, only: %i[edit]

    def index
      @services = Service.all
    end

    def new
      @service = Service.new
    end

    def create
      @service = Service.new(service_params)
      @service.user = current_user
      if @service.save
        redirect_to admin_services_path
      else
        redirect_to new_admin_service_path
      end
    end

    def edit; end

    private

    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:title, :description, :image, :user_id, :category_id)
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :set_user

    def show; end

    def edit
      @user = User.find(params[:id])
    end

    def update
      if @user.update(user_params)
        redirect_to admin_user_path, notice: t('users.updated')
      else
        redirect_to edit_admin_user_path, alert: t('users.not_updated')
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:firstname, :lastname, :description, :image)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'application_admin'
  # before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about
    @principal_user = User.where(firstname: 'Manon', lastname: 'Mathieu').first
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to admin_services_path
    else
      redirect_to new_admin_service_path, notice: 'Veuillez remplir tous les champs obligatoires'
    end
  end

  def edit; end

  def update
    if @service.update(service_params)
      redirect_to admin_services_path, notice: t('services.updated')
    else
      redirect_to new_admin_service_path, alert: t('services.not_updated')
    end
  end

  def destroy
    redirect_to admin_services_path, notice: t('services.destroyed') if @service.destroy
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :image, :user_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/home.html.erb
<div class="home-banner">
  <div class="col-8 mx-auto h-100">
    <div class="banner-container column">
      <h2 class="start-title mb-4">
        Bienvenue <strong><%= current_user.firstname if current_user%></strong><br>
        dans votre espace administrateur.
      </h2>

      <% if current_user %>
          <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
      <% else %>
        <%= link_to 'Se connecter', new_user_session_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<div class="for-more">

</div>

app/views/admin/services/_form.html.erb
<%= form_for @service do |f| %>

  <small id="serviceHelp" class="form-text text-muted my-2">
    Veillez à bien remplir les champs obligatoires pour valider l'enregistrement de votre novueau service.
  </small>

  <%= f.hidden_field :user_id %>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :category_id, "Catégorie", class: "control-label" %>
    <%= f.select :category_id, options_for_select(Category.all.collect { |c| [ c.name, c.id ] }, @service.category), { include_blank: false }, { class: 'form-control custom-select' } %>
  </div>

  <div class="form-group">
    <%= f.label :title, "Titre", class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
    <small id="serviceHelp" class="form-text text-muted">Facultatif</small>
  </div>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :description, "Description", class: "control-label" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :image, "Image", class: "control-label" %>
      <div class="custom-file custom-file-preview">
        <%= f.file_field :image, class: 'custom-file-input', accept: "image/png, image/jpeg", value: @service.image %>
        <label class="custom-file-label" for="file" data-browse="<%= t('actions.browse') %>"><%= t('actions.explore') %></label>
        <div class="image-preview">
          <%= image_tag @service.image.url.nil? ? 'default-image.png' : @service.image.url, class: 'img-fluid' %>
        </div>
      </div>
  </div>

  </div>

  <div class="form-group">
    <div class="text-center">
      <%= link_to t('actions.back'), :back, class: 'btn btn-secondary' %>
      <button type="submit" class="btn btn-primary"><%= t('actions.save') %></button>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  let input = document.querySelector(".custom-file-input");
  input.addEventListener("change", function() {
    const file = this.files[0];
    const source = URL.createObjectURL(file);
    const img = this.parentNode.querySelector('img');
    if (img !== null) {
        img.src = source;
    }
  })
</script>

app/views/admin/services/edit.html.erb
<div class="mt-3">
  <h2 class="text-center">Modifier un service</h2>
  <div class="col-6 mx-auto">
    <%= render "form" %>
  </div>
</div>

app/views/admin/services/index.html.erb
<div class="text-center mt-3">
  <h2>Mes services</h2>

  <div class="py-4">
    <p>Vous trouverez ici les différentes formules clef en main que je vous propose.<br>
    N’hésitez pas à me contacter pour en savoir plus, pour établir un devis ou pour un projet plus personnalisé.</p>
  </div>

  <%= link_to "+ Nouveau service", new_admin_service_path, class: "btn btn-primary mb-4" %>

  <div class="col-sm-12 col-md-8 col-lg-6 mx-auto">
    <%= render "services/list" %>
  </div>
</div>

app/views/admin/services/new.html.erb
<div class="mt-3">
  <h2 class="text-center">Ajouter un service</h2>
  <div class="col-6 mx-auto">
    <%= render "form" %>
  </div>
</div>

app/views/admin/shared/_navbar.html.erb
<div id="master-head">
  <div id="head-title" class="pb-3">

    <%= link_to admin_root_path do %>
      <h1>Manon Mathieu</h1>
      <h5>Rédactrice freelance  - Community Manager - Webdesigner</h5>
    <% end %>
  </div>

  <div id="head-navbar" class="border-bottom border-top">
    <ul class="navbar-list">
      <%= link_to admin_root_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.home') %></li>
      <% end %>
      <%= link_to admin_services_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.services') %></li>
      <% end %>
      <!-- <li class="navbar-item">Projets réalisés</li> -->
      <%= link_to about_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.about') %></li>
      <% end %>
      <%= link_to contact_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.contact') %></li>
      <% end %>
      <%= link_to admin_user_path(current_user), class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.profile') %></li>
      <% end %>
      <%= link_to root_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('actions.back_to_guest') %></li>
      <% end %>
    </ul>
  </div>
</div>

<script type="text/javascript">
  const navLinks = document.querySelectorAll(".navbar-link");

  navLinks.forEach(function(link){
    if (link.pathname === window.location.pathname) {
      link.classList.add("text-body")
    }
  });
</script>

app/views/admin/users/_form.html.erb
<%= form_for @user, url: admin_user_path(@user), html: { method: :put } do |f| %>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :firstname, "Prénom", class: "control-label" %>
    <%= f.text_field :firstname, class: "form-control" %>
  </div>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :lastname, "Nom", class: "control-label" %>
    <%= f.text_field :lastname, class: "form-control" %>
  </div>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :description, "Description", class: "control-label" %>
    <div class="mb-2"><small class="text-muted">Insérer un double slash "//" à la fin d'un pargraphe si vous souhaitez sauter une ligne.</small></div>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <span class="text-danger">*</span>
    <%= f.label :image, "Image", class: "control-label" %>
    <div class="custom-file custom-file-preview">
      <%= f.file_field :image, class: 'custom-file-input', accept: "image/png, image/jpeg", value: @user.image if @user.image %>
      <label class="custom-file-label" for="file" data-browse="<%= t('actions.browse') %>"><%= t('actions.explore') %></label>
      <div class="image-preview">
        <%= image_tag @user.image.nil? ? 'default-image.png' : @user.image.url, class: 'img-fluid' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="text-center">
      <%= link_to t('actions.back'), :back, class: 'btn btn-secondary' %>
      <button type="submit" class="btn btn-primary"><%= t('actions.save') %></button>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  let input = document.querySelector(".custom-file-input");
  input.addEventListener("change", function() {
    const file = this.files[0];
    const source = URL.createObjectURL(file);
    const img = this.parentNode.querySelector('img');
    if (img !== null) {
        img.src = source;
    }
  })
</script>

app/views/admin/users/edit.html.erb
<div class="mt-3">
  <h2 class="text-center">Modifier mon profil</h2>
  <div class="col-6 mx-auto">
    <%= render "form" %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="high-margin-top">
  <div class="col-sm-12 col-md-8 mx-auto">
    <% if current_user && current_user.admin %>
      <%= link_to edit_admin_user_path(current_user), class: "float-right" do %>
        <i class="fas fa-pen"></i>
      <% end %>
    <% end %>

    <h5><%= current_user.firstname %> <%= current_user.lastname %></h5>
    <p>
      <% current_user.description.split("//").each do |paragraph| %>
        <div class="mt-3">
          <p class="text-justify">
            <%= paragraph %>
          </p>
        </div>
      <% end %>
    </p>
    <div>
      <%= image_tag(current_user.image.url, alt: 'Image', class: "img-fluid", width: "380px") if current_user.image? %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Manon Mathieu</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="col-12">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
<div>hors body ? </div>
</html>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Manon Mathieu - Admin</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'admin/shared/navbar' %>
    <div class="col-12">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="col-12">
  <div class="mt-3 col-sm-12 col-md-8 mx-auto">

    <% if current_user && current_user.admin %>
      <%= link_to admin_user_path(current_user), class:"float-right pl-3" do %>
        <i class="fas fa-pen" title="<%= t('actions.update') %>"></i>
      <% end %>
    <% end %>

    <div class="about-content d-flex high-margin-top">
      <div class="about-image">
        <%#= image_tag(@principal_user.image.url, alt: 'Image', class: "img-fluid") if @principal_user.image? %>
        <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1595584889/Manon-dos_yjqjjk.png', alt: 'Image', class: "img-fluid") %>
      </div>

      <div class="about-description bg-white p-4">
        <h4>À PROPOS</h4>
        <%# @principal_user.description.split("//").each do |paragraph| %>
          <div class="mt-3">
            <p class="text-justify">
              <%#= paragraph %>
              Formée au journalisme et spécialisée en journalisme culturel j’ai fais mes premiers pas au sein de divers magazines parisiens avant de revenir m’installer en Provence, ma région natale. J’y ai poursuivi ma carrière en tant que chargée de communication dans le domaine du tourisme. En 2019, je choisis de partir parcourir le monde, une expérience que j’ai retransmise avec passion sur un site internet www.vansodyssey.com.</p>

              <p class="text-justify">Je reviens aujourd’hui en France pour proposer mes services en tant que freelance dans les domaines variés, mais si indispensables, de la communication. Influencée par mes voyages, mes expériences et rencontres, je vous propose des formules adaptées à votre personnalité et votre marque.</p>

              <p class="text-justify">Travaillons ensemble, main dans la main, au développement de votre société et/ou produit, en élaborant des outils de communications efficaces et adaptés.</p>
          </div>
        <%# end %>
      </div>
    </div>

  </div>

</div>

app/views/pages/contact.html.erb
<div class="high-margin-top">
  <div class="text-center mt-3">
    <h2>Contact</h2>

    <p>Pour tous renseignements ou pour recevoir un devis personnalisé, merci de me contacter par email :</p>

    <h4>manonmathieu.pro@gmail.com</h4>

  </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="h-100">
    <div class="banner-container column">
      <h2 class="start-title">Vous avez besoin de créer du contenu de<br class="d-none d-lg-block">
      qualité pour <strong>booster</strong> votre projet ?</h2>
      <h5 class="start-text">
        Je rédige vos contenus web, newsletters, articles de blog ou encore vos posts pour les réseaux sociaux.<br class="d-none d-lg-block">
        Je conçois vos mises en page de brochures, flyers, dossiers de presse et autres documents de communication.<br>
        Vous souhaitez une formule clé en main ? N’hésitez plus !
      </h5>
      <%= link_to contact_path, class: 'start-btn btn btn-primary' do%>
        <%= t('actions.contact_me') %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-12">
  <div class="for-more">
    <i class="fas fa-caret-down"></i>
  </div>

  <div class="home-services">
    <h3 class="text-center text-uppercase pb-4"><%= t('pages.services') %></h3>

    <div class="home-service-cards d-flex flex-wrap">
      <div class="home-service-card">
        <%= link_to services_path, class: "text-dark" do %>
          <i class="fas fa-pen-nib home-service-icon"></i>
        <% end %>
        <h5 class="text-uppercase"><%= t('home.redaction') %></h5>
        <p class="text-justify">Pour une rédaction sur mesure, choisissez ce service. Qu’importe le niveau de complexité de vos textes et le sujet à aborder, je serais en mesure de vous offrir des contenus de  qualité, adapté à votre projet, votre personalité.</p>
      </div>
      <div class="home-service-card">
        <%= link_to services_path, class: "text-dark" do %>
          <i class="fas fa-pencil-ruler home-service-icon"></i>
        <% end %>
        <h5 class="text-uppercase"><%= t('home.creation') %></h5>
        <p class="text-justify">Développez votre communication en bénéficiant des meilleurs outils actuels, adaptés à votre identité. Flyers, brochures, catalogues mais aussi sites web et réseaux sociaux, vous ne passerez plus inéperçu !</p>
      </div>
      <div class="home-service-card">
        <%= link_to services_path, class: "text-dark" do %>
          <i class="far fa-lightbulb home-service-icon"></i>
        <% end %>
        <h5 class="text-uppercase"><%= t('home.communication') %></h5>
        <p class="text-justify">Avec les communiqués et dossiers de presse, réalisés sur mesure, je vous aide à valoriser votre identité, votre projet, votre création  auprès des médias, de la presse et des acteurs de votre secteur.</p>
      </div>
    </div>
  </div>
  <div class="text-center mb-4">
    <%= link_to contact_path, class: 'start-btn btn btn-primary' do%>
      <%= t('actions.get_devise') %>
    <% end %>
  </div>

</div>

app/views/services/_list.html.erb
<%# @services.each do |service| %>
  <!-- <div class="card-product my-4"> -->
    <%#= cl_image_tag(service.image.url, alt: 'Image') if service.image? %>
    <!-- <div class="card-product-infos"> -->
      <!-- <h2><%#= service.title %></h2> -->
      <!-- <h4><%#= service.description %></h4> -->
    <!-- </div> -->
    <!-- <div class="actions-card"> -->
      <%# if current_user && current_user.admin %>
        <%#= link_to edit_admin_service_path(service) do %>
          <!-- <i class="far fa-edit" title="<%#= t('actions.update') %>"></i> -->
        <%# end %>
        <%#= button_to service_path(service), method: :delete, class: " text-danger btn btn-outline-light btn-sm" do %>
          <!-- <i class="far fa-trash-alt" title="<%#= t('actions.delete') %>"></i> -->
        <%# end %>
      <%# end %>
    <!-- </div> -->
  <!-- </div> -->
<%# end %>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596819554/site-web-Guide_utilisation_hdcriu.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Site Web + Guide d'utilisation</h2>
    <h4>Votre site clef en main avec un guide d'utilisation pour le maîtriser au quotidien.</h4>
  </div>
</div>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596819890/site-web-mises-a-jour_jg51at.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Site web + Mises à jours</h2>
    <h4>Votre site web clef en main ainsi que des mises à jour régulière pendant une durée déterminée.</h4>
  </div>
</div>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596819837/site-web-MAJ-CM_wbvesi.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Site Web + mises à jour + Réseaux sociaux</h2>
    <h4>Création de votre site web et gestion de vos actualités en ligne comme sur les réseaux sociaux.</h4>
  </div>
</div>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596823631/redaction_sur_commande_et_medias_wtnrvw.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Rédaction print & web</h2>
    <h4>Articles et dossiers pour des médias, contenus pour sites web, rédactions variées et à la demande.</h4>
  </div>
</div>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596799316/relation-presse-dossier-presse_oqhbbn.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Dossier de presse et communication ponctuelle</h2>
    <h4>Conception de vos communiqués et dossiers de presse, création des documents de communication dédiés à un événement ponctuel.</h4>
  </div>
</div>

<div class="card-product my-4">
  <%= cl_image_tag('https://res.cloudinary.com/dsxhzsgsy/image/upload/v1596819919/docs-de-com_qlqfvc.jpg', alt: 'Image', class: "img-fluid") %>
  <div class="card-product-infos">
    <h2>Vos documents de communications</h2>
    <h4>Création de tous types de documents de communication personnalisés : flyer, brochure, catalogue...</h4>
  </div>
</div>

app/views/services/index.html.erb
<div class="col-12">
  <div class="text-center mt-3">
    <h2>Mes services</h2>
    <div class="py-4">
      <p>Vous trouverez ici les différentes formules clef en main que je vous propose.<br>
      N’hésitez pas à me contacter pour en savoir plus, pour établir un devis ou pour un projet plus personnalisé.</p>
    </div>

    <div class="col-sm-12 col-md-8 col-lg-6 mx-auto">
      <%= render "list" %>
    </div>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="<%= t('actions.close') %>"><i class="fas fa-times alert-close-fa"></i></button>
    <%= flash[:error] %>
  </div>
<% end %>
<% if notice %>
  <div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="<%= t('actions.close') %>"><i class="fas fa-times alert-close-fa"></i></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="<%= t('actions.close') %>"><i class="fas fa-times alert-close-fa"></i></button>
    <%= alert %>
  </div>
<% end %>

<script type="text/javascript">
  let close = document.querySelector(".alert-close-fa");
  if (close !== null) {
    close.addEventListener("click", function() {
      document.querySelector(".alert").classList.add("d-none");
    })
  }
</script>

app/views/shared/_navbar.html.erb
<div id="master-head">
  <div id="head-title" class="pb-3">

    <%= link_to root_path do %>
      <h1>Manon Mathieu</h1>
      <h5>Rédactrice freelance  - Community Manager - Webdesigner</h5>
    <% end %>
  </div>

  <div id="head-navbar" class="border-bottom border-top">
    <ul class="navbar-list">
      <%= link_to root_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.home') %></li>
      <% end %>
      <%= link_to services_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.services') %></li>
      <% end %>
      <!-- <li class="navbar-item">Projets réalisés</li> -->
      <%= link_to about_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.about') %></li>
      <% end %>
      <%= link_to contact_path, class: "navbar-link" do %>
        <li class="navbar-item"><%= t('pages.contact') %></li>
      <% end %>
    </ul>
  </div>
</div>

<script type="text/javascript">
  const navLinks = document.querySelectorAll(".navbar-link");

  navLinks.forEach(function(link){
    if (link.pathname === window.location.pathname) {
      link.classList.add("text-body")
    }
  });
</script>